#!/bin/sh

./julius/bin/julius -C julius/hmm_mono.jconf -gram data/kaden -input mic -lv 1000 -zc 1 -rejectshort 800 -module &
echo "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
./juli2ir &

