#!/bin/sh

while true; do
	./stop
	./julius/bin/julius -C julius/hmm_mono.jconf -gram data/kaden -input mic -lv 1000 -zc 1 -rejectshort 800 -module > log.txt &
	sleep 2
	./juli2ir &
	sleep 3600
done

